<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE unions [
    <!ELEMENT unions (union+)>
    <!ELEMENT union (name,afifiliates,headquarter,sectors,spokesman)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT afifiliates (#PCDATA)>
    <!ELEMENT headquarter (#PCDATA)>
    <!ELEMENT sectors (sector+)>
    <!ELEMENT sector (name,city)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT spokesman (#PCDATA)>
    <!ATTLIST union id ID #REQUIRED>    
]>
<unions>
    <union id="a53">
        <name>CGY</name>
        <afifiliates>1200</afifiliates>
        <headquarter>C/ Trévere 25</headquarter>
        <sectors>
            <sector>
                <name>Enseñanza</name>
                <city>Madrid</city>
            </sector>
        </sectors>
        <spokesman>Victor</spokesman>
    </union>
    <union id="a55">
        <name>Raimon</name>
        <afifiliates>1400</afifiliates>
        <headquarter>C/ Calzada 25</headquarter>
        <sectors>
            <sector>
                <name>Militar</name>
                <city>Madrid</city>
            </sector>
        </sectors>
        <spokesman>Mark</spokesman>
    </union>
</unions>