=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/Library.dtd
<!-- 
  DTD for Library Management System
  Defines structure for book catalog
-->

<!-- Root element: contains one or more books -->
<!ELEMENT library (book+)>

<!-- Book element structure -->
<!ELEMENT book (title, author+, publication, genre*, isbn, price, description?)>

<!-- Title is simple text -->
<!ELEMENT title (#PCDATA)>

<!-- At least one author, possibly more -->
<!ELEMENT author (firstname, lastname, nationality?)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>

<!-- Publication information -->
<!ELEMENT publication (publisher, year, edition?)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT edition (#PCDATA)>

<!-- Genre: optional, multiple allowed -->
<!ELEMENT genre (#PCDATA)>

<!-- ISBN and price -->
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!-- Optional description with mixed content -->
<!-- Tienes que garantizar que description pueda tener dentro etiquetas HTML -->
<!ELEMENT description (#PCDATA)*>

<!-- Attribute declarations -->

<!-- Book attributes -->
<!ATTLIST book
    id          ID      #REQUIRED
    available   (yes|no) "yes"
    language    CDATA   "en"
    format      (paperback|hardcover|ebook) "paperback"
>

<!-- Price attributes -->
<!ATTLIST price
    currency    (USD|EUR|GBP) "EUR"
    tax-included (yes|no) "no"
>

<!-- Genre attribute -->
<!ATTLIST genre
    main-genre CDATA #IMPLIED
>

<!-- Entities for common text -->
<!ENTITY library-name "City Central Library">
<!ENTITY default-currency "EUR">

=== XenoDT/vscode/LenguajeMarcas/Ejs/CSS/xml/Library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "Library.dtd">
<library>
    <book id="AA" available="yes" language="en" format="ebook">
        <title>Reb de los pollos</title>
        <author>
            <firstname>Goku</firstname>
            <lastname>Mario</lastname>
            <nationality>Jp</nationality>
        </author>
        <publication>
            <publisher>Norma</publisher>
            <year>789</year>
            <edition>2.2</edition>
        </publication>
        <genre main-genre="Shounen">Sheinen</genre>
        <isbn>sdmfs0vf9uwe0vj0sdc</isbn>
        <price currency="EUR" tax-included="no">20.99</price>
        <description>No one will know</description>
    </book>
    <book id="Ac" available="yes" language="en" format="ebook">
        <title>gjkpsdfg</title>
        <author>
            <firstname>Goku</firstname>
            <lastname>Mario</lastname>
            <nationality>Jp</nationality>
        </author>
        <publication>
            <publisher>Norma</publisher>
            <year>788</year>
            <edition>2.3</edition>
        </publication>
        <genre main-genre="Shounen">Sheinen</genre>
        <isbn>sdmfs0vf9uwe0vj0sdc</isbn>
        <price currency="EUR" tax-included="no">21.99</price>
        <description>No one will know</description>
    </book>
</library>
